<style>
    .modal-btn {
        border-radius: 0.7rem;
    }

    .modal-btn-clear {
        border: 1px solid #000;
    }
</style>

<div class="modal " id="addProductModal">
    <a href="javascript:hideProductModal()" class="modal-overlay" aria-label="Close"></a>
    <div class="modal-container">
        <div class="modal-header ">
            <a href="javascript:hideAddProductModal()" class="btn btn-clear btn-error float-right" aria-label="Close"></a>
            <div class="modal-title h5 text-center" id="frm-title">New Product</div>
        </div>
        <div class="modal-body ">

            <div class="content">
                <form id="product-frm">
                    <div class="columns">

                        <div class="column col-6 col-md-12">
                            <!-- ID NUMBER -->
                            <div class="form-group">
                                <label class="form-label" for="in-prod-id">ID</label>
                                <input class="form-input" type="text" id="in-prod-id" placeholder="Autogenerated" disabled>
                            </div>
                            <!-- Bday -->
                            <div class="form-group " id="bday-frm">
                                <label class="form-label" for="bday">Birthdate</label>
                                <input class="form-input" type="date" id="bday" name="bday" placeholder="">
                            </div>


                        </div>
                        <div class="column col-6 col-md-12">
                            <!-- Type -->
                            <div class="form-group" id="type-frm">
                                <label class="form-label" for="type">Type</label>
                                <select class="form-select" id="type" name="type">
                                    <option value="0">PIG</option>
                                    <option value="1">COW</option>
                                </select>
                            </div>

                            <!-- Weight -->
                            <div class="form-group mt-2" id="weight-frm">
                                <label class="form-label" for="weight">Weight</label>
                                <input class="form-input" type="number" id="weight" name="weight" placeholder="Kg">
                            </div>
                        </div>

                    </div>
                    <div class="columns">
                        <div class="column col-6 col-md-12 col-mr-auto col-ml-auto">
                            <!-- Preggy -->
                            <label class="form-label" for="in-prod-preg">Pregnant</label>
                            <div class="input-group" id="preg-frm">
                                <select class="form-select" id="pregnant" name="pregnant" onchange="manageDueField(this)">
                                    <option value="0">No</option>
                                    <option value="1">Yes</option>
                                </select>
                                <input class="form-input" id="due" name="due" type="date" placeholder="Due Date" disabled>

                            </div>
                        </div>
                    </div>
                </form>
                <br />
                <div class="columns mt-2">
                    <div class="column col-3  hide-md"></div>
                    <div class="column col-3 col-md-12  " id="add-prod-btn"><a href="javascript:sendData()" class="btn btn-primary text-light btn-lg " id="prod-btn-send" style="width: 100%;border-radius:10px;">ADD</a></div>
                    <div class="column col-1 col-md-12 mt-2 mb-2"></div>
                    <div class="column col-3 col-md-12  " id="add-prod-btn"><a href="javascript:hideAddProductModal()" id="prod-btn-cancel" class="btn btn-link text-light btn-lg text-dark" style="width: 100%;border-radius:10px; border:1px solid #000;">CLEAR</a></div>
                    <div class="column col-2  hide-md"></div>
                </div>
            </div>

        </div>
        <div class="modal-footer">

        </div>
    </div>
</div>
    <script type="text/javascript">
        var addProductModal = document.getElementById('addProductModal');


        function showAddProductModal() {
            resetForm1('#product-frm');
            showModal(addProductModal);
            revertForm();
        }

        function showEditProductModal() {
            showModal(addProductModal);
        }

        function hideAddProductModal() {
            hideModal(addProductModal);
            removeErrorField();
            resetForm('product-frm');
        }

        function manageDueField(val) {
            if (val.value == 1) {
                $("#due").prop('disabled', false);
            } else {
                $("#due").prop('disabled', true);
                $('#due').val('');
            }
            console.log(val.value);
        }



        function onSendBtn(id) {
            showBtnLoading(id);
            disableBtn(id);
        }

        function onReceiveBtn(id) {
            hideBtnLoading(id);
            enableBtn(id);
        }

        function showError() {
            alertify.set('notifier', 'position', 'top-center');
            alertify.error('Failed to Add');
        }

        function showSucess() {
            alertify.set('notifier', 'position', 'top-center');
            alertify.success('Success');
        }

        function updateErrorField(arrError) {
            if ('age' in arrError) {
                $('#age-frm').addClass('has-error');
            }
            if ('pregnant' in arrError && 'due' in arrError) {
                $('#preg-frm').addClass('has-error');
            }
            if ('bday' in arrError) {
                $('#bday-frm').addClass('has-error');
            }
            if ('type' in arrError) {
                $('#type-frm').addClass('has-error');
            }
            if ('weight' in arrError) {
                $('#weight-frm').addClass('has-error');
            }
        }

        function removeErrorField() {
            $('#age-frm').removeClass('has-error');
            $('#preg-frm').removeClass('has-error');
            $('#bday-frm').removeClass('has-error');
            $('#type-frm').removeClass('has-error');
            $('#weight-frm').removeClass('has-error');
        }


        function sendData(action = 0, id = null) {
            var endpoint = '<?php echo base_url(); ?>/product/create';
            if (action == 1) {
                endpoint = '<?php echo base_url(); ?>/update/' + id;
            }
            onSendBtn("#prod-btn-send");
            removeErrorField();
            $.ajax({
                url: endpoint,
                type: 'POST',
                dataType: 'JSON',
                contentType: 'application/json',
                data: frmToJSON('#product-frm'),
                headers: {
                    "Authorization": "Bearer " + getCookie("token")
                },
                error: function(xhr, status, error) {
                    var errdata = xhr.responseJSON;
                    updateErrorField(errdata['messages']);
                    onReceiveBtn("#prod-btn-send");
                    showError();
                    if (xhr.status == 401) {
                        console.log("UNAUTHORIZED");
                        logout();
                    }
                },
                success: function(response) {
                    console.log('Success');
                    onReceiveBtn("#prod-btn-send");
                    removeErrorField();
                    showSucess();
                    hideAddProductModal();
                    fetchData();
                }
            });
        }
    </script>

    <script type="text/javascript">
        function fetchSingle(id) {
            $.ajax({
                url: '<?php echo base_url(); ?>/find/' + id,
                type: 'POST',
                headers: {
                    "Authorization": "Bearer " + getCookie("token")
                },
                error: function(xhr, status, error) {
                    popError(xhr.responseJSON['messages']['error']);
                    // hideBtnLoading('#btn-del-yes');
                    if (xhr.status == 401) {
                        console.log("UNAUTHORIZED");
                        logout();
                    }
                },
                success: function(data) {
                    setEditFormContent(data);
                }

            });
        }

        function setEditFormContent(arrData) {
            var txt = "javascript:sendData(1," + arrData['id'] + ")";
            $('#prod-btn-send').attr("href", txt);
            $("#frm-title").text("Edit Record");
            $("#prod-id").val(arrData['id']);
            $('#bday').val(arrData['bday']);
            $('#type').val(arrData['type']);
            $('#weight').val(arrData['weight']);
            $('#pregnant').val(arrData['pregnant']);
            if (arrData['pregnant'] == 1) {
                document.getElementById('due').disabled = false;
            } else {
                document.getElementById('due').disabled = true;
            }
            $('#due').val(arrData['due']);
            $('#prod-btn-send').text("Update");
            showEditProductModal();

        }

        function revertForm() {
            $("#frm-title").text("New Product");
            $('#prod-btn-send').attr("href", "javascript:sendData()");
            $('#prod-btn-send').text("Add");
            document.getElementById('due').disabled = true;
        }
    </script>